version: '3'

services:
  dashboardDB:
    image: postgres:15.3
    container_name: from-builder
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fromBuilder
    volumes:
      - ./postgres:/var/lib/postgresql/data
